### ISSUE TITLE
Data and pretrained model usage

### ISSUE THREAD

**Issue by PhucNDA** [OpenSun3D/OpenSun3D.github.io#3]
Hi again, thanks for the detailed clarification.

After our team discussion, we have many concerns about training data and published pretrained model.

As the challenge stated: "_For this challenge, in order to develop or train your model, you can only use the scenes provided in the ARKitScenes Training set or the Development set we provide_". Is it mean that we are allowed to use only the scene provided in the ARKitScenes and the 3DOD annotations?
Can we use open-source pretrained models such as [OpenScene](https://pengsongyou.github.io/openscene) trained on [Scannetv2 ](http://www.scan-net.org/)or [CLIP](https://github.com/openai/CLIP), Image backbones pretrained on ImageNet etc.? If yes, are we allowed to use additional indoor datasets such as Scannetv2, [Matterport3D](https://niessner.github.io/Matterport/), etc.? We don't quite sure about the challenge regulation (dataset, pretrained model usage). Please carify about the challenge regulations more.

Looking forward to the respone.
Thank you,
PhucNDA

**Comment by yashbhalgat** [comment]
I have the same questions as above. @aycatakmaz, I was wondering if you could kindly advise here. Thank you!

**Comment by francisengelmann** [comment]
Hi all,
You are free to use all kinds of pre-trained models (OpenScene, CLIP etc.).
You can also pre-train on other additional datasets - the goal is to see what is possible with current methods and datasets.
We will update the instructions accordingly - thanks for asking :)

**Comment by yashbhalgat** [comment]
Wonderful, thanks for confirming!
